MODULE module_driver_constants
  INTEGER, PARAMETER :: IWORDSIZE = 4
  INTEGER, PARAMETER :: RWORDSIZE = 4
  INTEGER, PARAMETER :: DWORDSIZE = 8
  INTEGER, PARAMETER :: LWORDSIZE = 4
END MODULE module_driver_constants
